day16_layout_views/task2/Models/PersonModel.cs
namespace task2.Models;

public class PersonModel
{
    public Name FullName { get; set; }
    public int Age { get; set; }

    public PersonModel(Name fullName, int age)
    {
        FullName = fullName ?? throw new ArgumentNullException(nameof(fullName));
        Age = age;
    }

    public class Name
    {
        public string First { get; set; }
        public string Last { get; set; }

        public Name(string first, string last)
        {
            First = first ?? throw new ArgumentNullException(nameof(first));
            Last = last ?? throw new ArgumentNullException(nameof(last));
        }
    }
}

day16_layout_views/task2/ViewModels/ErrorViewModel.cs
namespace task2.ViewModels;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

day16_layout_views/task2/Controllers/HomeController.cs
using System.Collections;
using System.ComponentModel;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using task2.Models;
using task2.ViewModels;

namespace task2.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    private IEnumerable<PersonModel> AllPersons()
    {
        return new PersonModel[]
        {
            new(new PersonModel.Name("Lukas", "Knudsen"), 23),
            new(new PersonModel.Name("Mads", "Bjerg"), 26),
            new(new PersonModel.Name("Mike", "Bang"), 25),
            new(new PersonModel.Name("Berta", "Vazquez"), 21)
        };
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public IActionResult ShowAll()
    {
        return View(AllPersons());
    }

    [HttpGet]
    public IActionResult ShowOne()
    {
        return View(AllPersons().ToList()[0]);
    }

    // -----------------------------------------------------------------------------------------------------------------

    [HttpGet]
    public IActionResult Privacy()
    {
        return View();
    }

    [HttpGet]
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

day16_layout_views/task2/ViewComponents/OnePersonViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using task2.Models;

namespace task2.ViewComponents;

public class OnePersonViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(PersonModel p)
    {
        if (p.Age < 18)
        {
            p.FullName.Last = p.FullName.Last.Replace(p.FullName.Last, new string('*', p.FullName.Last.Length));
        }

        return View(p);
    }
}

day16_layout_views/task2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

day16_layout_views/task2/Views/Home/ShowAll.cshtml
@model IEnumerable<PersonModel>

@{
    ViewData["Title"] = "All Persons";
}

<h2>All persons</h2>
<ul>
    @foreach (PersonModel p in Model)
    {
        <li>@await Component.InvokeAsync("OnePerson", p)</li>
    }
</ul>

day16_layout_views/task2/Views/Home/ShowOne.cshtml
@model PersonModel

@{
    ViewData["Title"] = "One person";
}

<h2>One person</h2>
@await Component.InvokeAsync("OnePerson", Model)